management:
  security:
    enabled: false
server:
  port: 8012
---
management:
  security:
    enabled: false
spring:
  profiles: dev
server:
  port: 8015
---
management:
  security:
    enabled: false
spring:
  profiles: test
server:
  port: 8014